# baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Burak Sekili
paginate: 5
theme: charlolamode

menu:
    main:
        - name: ""
          url: /
        - name: ""
          url: /
        - name: ""
          url: /

params:
    author: Burak Sekili

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Burak Sekili
        description: |

          I am Burak, a software engineer working at [![Tyk](images/tyk-logo.png)](https://tyk.io/), who is interested in distributed systems and developer tooling. 

          At [![Tyk](images/tyk-logo.png)](https://tyk.io/), I work on

            - [Tyk Operator](https://github.com/TykTechnologies/tyk-operator/), Kubernetes Controller managing Tyk resources on Kubernetes.
            - [Tyk Helm Charts](https://github.com/TykTechnologies/tyk-helm-chart/), Helm Charts to deploy Tyk stack on Kubernetes.
            - [Tyk Schemas](https://marketplace.visualstudio.com/items?itemName=TykTechnologiesLimited.tyk-schemas), a VsCode extension providing JSON validation for files used by Tyk products.
            - Other internal DX projects...

          Find me on 👇

        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons: null
    mainSections: null
      

    socialIcons:
        - name: github
          url: "https://github.com/buraksekili"
        - name: linkedin
          url: "https://www.linkedin.com/in/sekili/"
        - name: twitter
          url: "https://twitter.com/buraksekili"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
